name: time_tracker
description: "Professional Time Tracker App by NavShock Studio - Track your productivity with precision"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8

  # Local Storage (versiones fijas y compatibles)
  shared_preferences: 2.5.3
  hive: 2.2.3
  hive_flutter: 1.1.0

  # State Management
  provider: 6.1.5+1

  # Networking
  http: 1.5.0

  # AdMob para monetización
  google_mobile_ads: 5.3.1
  
  # Utilidades
  intl: ^0.19.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Para asegurar que la app funcione en todas las densidades de pantalla
  # Flutter automáticamente selecciona el recurso correcto según la densidad
  
  # Assets (si tienes imágenes o recursos)
  # assets:
  #   - assets/images/
  #   - assets/icons/